name: Frontend SonarQube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: frontend-react
        run: npm install
        
      - name: Build App
        working-directory: frontend-react
        run: npm run build
        
      - name: Snyk Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          command: test
          args: --file=frontend-react/package.json --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Run tests with coverage
        run: npm test -- --coverage
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=frontend-react/src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
