name: Frontend SonarQube
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend-react
        run: npm install

      - name: Run tests with coverage
        working-directory: frontend-react
        run: |
          npm test -- --coverage --watchAll=false

      - name: Debug coverage
        working-directory: frontend-react
        run: |
          echo "Checking coverage folder"
          ls -R
          ls -R coverage || echo "NO COVERAGE FOLDER"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: frontend-react
          args: >
            -Dsonar.projectKey=hrishi760_frontend
            -Dsonar.organization=hrishi760
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
